path = ../../../3rdparty/SFML-2.5.1
select_move_delete:
	g++ ./select_move_delete.cpp -std=c++11 -o select_move_delete.exe -I $(path)/include -L $(path)/lib/ -lsfml-graphics -lsfml-window -lsfml-system 
